### ISSUE TITLE
Add a current date next to the clock

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#80] opened 2019-10-16 11:37 UTC
**Is your feature request related to a problem? Please describe.**
You cannot view the current date.

**Describe the solution you'd like**
Implement a date icon (left or right of the clock, to show the current day,month and year (possibly also day with short names like Mon, Tue...)

![Date-Logo-_WEG_October-12-150x150](https://user-images.githubusercontent.com/50620416/66915699-f19da580-f019-11e9-8751-905a40b2e825.png)
Icon source: http://blog.ilwucu.org/2013/weekend-guide-october-11-13-2013/date-logo-_weg_october-12/

**Comment by UriahShaulMandel** [comment] 2019-10-16 13:31
I guess it's important, but I'm not sure where is the best place to put it... 
I really like the big clock in the center, I think it looks great

Perhaps that clicking on the clock will bring up a new screen of date, clock with seconds, and upcoming alarms and pills? what do you think?

**Comment by aha999** [comment] 2019-10-17 19:09
I don't know... It would be nice to have the current date or name of the day somewhere...

**Comment by aha999** [comment] 2019-10-22 20:34
It could still be in the center by default, but the calendar box could be enabled optionally.

**Comment by aha999** [comment] 2019-11-17 14:02
You meant something like this after pressing the clock ?

![photo_2019-11-17_14-56-58](https://user-images.githubusercontent.com/50620416/69008467-2ff4f000-094b-11ea-9b81-f1e7c1500a57.jpg)

**Comment by Aokromes** [comment] 2020-01-06 08:30
maybe even day number and name on one side and month name on the other.

**Comment by UriahShaulMandel** [comment] 2020-01-06 19:53
Closing this issue, a duplicate of  #52

**Closed by UriahShaulMandel** 2020-01-06 19:53 UTC
Labels: enhancement
